### ISSUE TITLE
Cointoolkit transaction infinitely loads even if transaction is completed

### ISSUE THREAD

**Issue by captainbuckkets** [peercoin/cointoolkit#16]
Tested on testnet only, but when generating a transaction and going to broadcast results in infinite loading saying "Please wait, loading..." even after the transaction was broadcasted and visible on an explorer.

![image](https://user-images.githubusercontent.com/24922789/72935082-4d1eb400-3d2a-11ea-829d-fdd249801cbd.png)

Said transaction after being broadcasted: https://chainz.cryptoid.info/ppc-test/tx.dws?867856.htm

**Comment by peerchemist** [comment]
I confirm the issue.

**Comment by captainbuckkets** [comment]
Perhaps was limited to Firefox specifically.  Chrome did not have the same issue.  Maybe it was client side but I am unsure since I cannot replicate it, but chem said he was previously aware of this issue.

**Comment by captainbuckkets** [comment]
Nevermind, it is still looping.  This time it didn't throw an error I had previously.  I did replicate it then in this case.
